### PR TITLE
add a reveal password icon

### PR DESCRIPTION
**Pull request by alek-p**
Thanks for your work on this great project!

I needed a way to see the password as it's being entered which helps with long and/or complicated passwords so I've added that functionality to the password template.

Hopefully others find this useful.

### CODE REVIEW

**Comment by robinmoisson** [comment]
Thank you for the PR, I think that's a good idea!

UX-wise it's a bit confusing to me to have 2 checkboxes on top of each other, I think it'd be clearer to have the little eye icon straight in the password input - for example in that bitwarden prompt:

image

Feel free to do it in if you'd like, otherwise I'll do it sometime in the next couple of weeks and merge. Thanks again for the idea.

**Comment by alek-p** [comment]
I've implemented this over the weekend I'll create a PR soon

**Comment by alek-p** [comment]
PR updated in place. Here are some screenshots of the results
Screenshot 2024-02-26 at 14 26 08
Screenshot 2024-02-26 at 14 26 17

**Comment by alek-p** [comment]
don't mind the changed "remember me" text, i didn't modify it in the default template but was using my project's template as the example

**Comment by robinmoisson** [comment]
Looks great! I have a few more thoughts, but if you're ok with the licensing thing and wanna stop here I'm fine with merging and implementing them myself too (or feel free to change them if you'd like, just no pressure!).

One technical thing:
- I think the project should rely as little as possible external resources (among other reasons to allow offline use), so we'd need to embed the two icons inside the file itself and remove the loading from the cdn. To keep the file as light as possible we can extract those two icons and not load the whole FA css file.

Two licensing thoughts:
- I wanted to make sure FontAwesome license allows to embed their icons in an open source project with MIT & non-MIT licenses, and under what conditions. I get the impression [it's fine as long as there's attribution](https://fontawesome.com/license/free)? Then maybe there can be a comment alongside the embedded icons pointing toward the FA website
- I'm thinking of changing the staticrypt license to something other than MIT - possibly AGPL, which means anyone can use staticrypt as they want if their code is realized as FOSS, and adding that solo people can do whatever they want and corporations that want to keep their code closed-source can buy the code under a license that allows them to do that. I'm still early in researching that topic but I'd rather let people submitting PRs know about this before merging them to at least get a principled agreement, if not a legalese one, so you can make a conscious choice. I'll open an issue to gather feedback on this before making a change. Are you ok basically giving all rights to your code in this PR to the staticrypt project and to myself, to do as I see fit?

**Comment by alek-p** [comment]
Yup, I'm fine with whatever licence you end up choosing.

As far as pulling the icons in - I'm happy to do that but not sure when I'd be getting to it - so if you beat me to it no problem otherwise I'll get to it eventually

**Comment by robinmoisson** [comment]
Done & published as minor bump - thanks for the idea & PR @alek-p!

image

**Pull request closed without merging**
