### PR TITLE
Webcrypto

### PR DESCRIPTION
**Pull request by tarpdalton**
this removes the dependency on crypto.js and uses the webcrypto API. I haven't updated the CLI with the new logic, but I wanted to open this PR with what I had so far. #20

### CODE REVIEW

**Comment by tarpdalton** [comment]
It looks like you can't use a the web crypto API in a node module. So I don't think we can remove the crypto.js dependency from the CLI.

**Comment by epicfaace** [comment]
@tarpdalton can't you continue to use crypto-js in the node module, but just change the code in the template HTML file to use the web crypto API (and fallback to asynchronously loading crypto-js if needed?)

**Comment by tarpdalton** [comment]
@epicfaace yeah we could do that. We would just have to make sure the something encrypted by crypto-js can be decrypted by webcrypto correctly

**Comment by DanielRuf** [comment]
I guess this can be revisited now since Node.js 15 has a Webcrypto module now. Current stable Node.js version is 16.
https://nodejs.org/api/webcrypto.html


Also there is this package: https://www.npmjs.com/package/node-webcrypto-ossl

**Comment by tarpdalton** [comment]
thats cool. yeah we should use the webcrypto api in the node, and then crypto-js can be fully removed

**Comment by tarpdalton** [comment]
i got the cli working with node webcrypto api. crypto-js is removed. I don't really use this lib so I can't test it out, but it worked for some simple things. Someone should test it out before it merges

**Comment by robinmoisson** [comment]
We now finally rely on WebCrypto in StatiCrypt! The code was merged in #164 , it's pretty noisy due to wanting to be as compatible as possible with 2.x custom templates, but it'll get much cleaner in 3.x (the WIP branch is [already here](https://github.com/robinmoisson/staticrypt/tree/v3)).

Thank you very much for opening and updating this PR over the years, it's been a good sanity check for me to read your approach here and useful for the final implementation. As a (very small) token of gratitude, I added your name in the "Thank you! :pray:" README section. Thanks!

**Pull request closed without merging**
