### PR TITLE
Fix all security flaws

### PR DESCRIPTION
**Pull request by clydebottoms**
CVSS-3 0 7
Hello,

There are various security issues in your project that a respectable security researcher and I have discovered while doing a cursory glance at your project's code. The most notable example is at [`cryptojsEngine#L42-53`](https://github.com/robinmoisson/staticrypt/blob/main/lib/cryptoEngine/cryptojsEngine.js#L42) where you use a laughably low number of PBKDF2 iterations, so much so that we can only assume this project is intentionally insecure and quite possibly NSA sponsored considering they supported 3DES despite knowing it was unsafe!

Do not fret, for I have so graciously solved all of these issues for you in this PR, giving you the benefit of the doubt and assuming these were simply mistakes and not an intentional subversion of national security. It is ready to be merged once you point out any `nit`s you might have :+1:

### CODE REVIEW

**Comment by clydebottoms** [comment]
@robinmoisson  Hello,
I have now given you three days' notice. If you do not fix these security flaws either by manually fixing them or by clicking the merge button below, I will be forced to report you to the department of homeland security.

I have fixed the merge conflicts with this PR so if you please you may simply click "merge."

Happy taco Tuesday
Sincerely, Clyde P Bottoms.
A security researcher at IBM

**Comment by clydebottoms** [comment]
@Angelore @Chasecares @eldercare3310 Hello,
If you would like to state your objections to this PR, please voice your opinions here.

**Comment by clydebottoms** [comment]
Greetings again,
I have generated a CVSS score for this vulnerability. It has been calculated as 7.5, meaning it should be addressed immediately.

CVSS-3 0 7
> The vulnerability has been assigned a CVSS score of 7.5 (High). CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N/E:H/RL:U/RC:C/CR:H.

If you have any questions or concerns or are a user of this project in production, please email me at clydepbottoms@security.ibm.com

**Comment by oleteacher** [comment]
If this is "possibility" an NSA project, why would one report NSA to homeland security?

I am just a simple minded Schook teacher, so please forgive my lack of knowledge about how this script. Like many, I use it to protect personal web pages?

**Comment by clydebottoms** [comment]
Susan,
Firstly to ease your concern, if there is no substantial harm caused by all of the information currently "password-protected bv this sottware being leaked, then you are perfectly fine. However, it would be best if you treated anything password protected by this software as essentially "not password-protected," as it would be trivial to brute-force any password that is not as long as, say, the equivalent of an ssh or gpg private key (which yours probably isn't.) So instead of this software, I recommend using the standardized [HTTP Basic Authentication](https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/), which will password-protect your website without the need for any Javascript.

Secondly, I likened the treatment of this project's PBKDF2 iterations to the intentionally subverted cryptography supported by the NSA years ago, but that doesn't necessarily mean it's an NSA project. Additionally, due to the separation of power in the United States, it is possible to report NSA misdeeds to the Department of Homeland Security.

I hope this helps.
Sincerely, Clyde P Bottoms.
A security researcher at IBM

**Comment by robinmoisson** [comment]
Hey @clydebottoms,

Thanks for helping improve the project's security. I'd rather you opened a joke PR (for anyone else reading this, the PR is deleting all files in the project, not making any other suggestion to the code) and that I get the info about a possible security flaw, than not get the info at all.

**The concern of this PR in a few words:** we hash the password multiple times with PBKDF2 before using it as a key to encrypt the data. The concern is that we should increase the iteration count a lot to make the process slower, so brute-force attacks are more expensive to do. As it stands they are easier than they could/should be, so passwords are weaker. How big of an issue that is for you depends on your password's strength and your threat model (who you're protecting from).

**Remediation steps:** I was hoping I could just increase the number of iterations from 1k to 600k and call it a day, but this has other consequences that need to be considered (it's a breaking change depending on how it's done, the recommended 600k take ~10s to run on my machine to decrypt/encrypt). So I'm working on understanding exactly what the real world impacts of these settings are, what it means depending on your particular situation, and what the best way to go forward is.

I'm going to post an long issue on the topic to share the process and invite feedback in the coming days, but I hope this comment gives a little visibility before that.

---

@clydebottoms regarding the rest of this thread: I was ok with your opening message and PR, am ok with the CVSS one, but feel the tone of the rest of your messages is out of place. The threat of reporting to homeland security doesn't make any sense and there is no "3 day notice" - this is free software provided as-is on an MIT license. Tagging people downvoting a PR deleting the repo to ask for explanation is not ok either.

For reference, the context of the administration of this repo is outlined in the README in the ["Opening PRs and issues"](https://github.com/robinmoisson/staticrypt#opening-prs-and-issues) section ("If you find a serious security bug please open an issue, I'll try to fix it relatively quickly."). I also try to be as transparent as possible on the security aspects of StatiCrypt and whether you should use it in the ["Is it secure"](https://github.com/robinmoisson/staticrypt#is-it-secure) section.

These comments therefore seem neither in good faith nor constructive to me, and I invite you to tread lightly or I will block you from commenting here. I'd rather be transparent early about that as well.

**Comment by robinmoisson** [comment]
The issue is now open, so I'm closing this PR.

**Pull request closed without merging**
